server:
  port: 8888

spring:
  application:
    name: plato-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # default url
        cluster-name: GZ
        username: nacos
        password: nacos
    loadbalancer:
      nacos:
        enabled: true # 启用nacos负载均衡配置同集群优先 同一集群下是随机策略 @LoadBalancerClient无效