server:
  port: 8087
  servlet:
    context-path: /api

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.linklyze: debug
  pattern:
    # 要交双引号
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p ${PID:-} [%15.15t] %-40.40logger{39} %L : %m%n"
