spring:
  profiles:
    active: dev
  application:
    name: linklyze-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVERS:localhost:8848}
        cluster-name: ${NACOS_CLUSTER_NAME:GZ}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
    loadbalancer:
      nacos:
        # 启用nacos负载均衡配置同集群优先 同一集群下是随机策略 @LoadBalancerClient无效
        enabled: true
    # gateway config
    gateway:
      routes:
        - id: linklyze-account # 路由id，自定义 唯一即可
          uri: lb://linklyze-account # lb://服务名称 loadbalance服务均衡
          # 路由断言 判断请求是否符合当前路由规则的条件 不符合访问404
          # 官方文档 https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#gateway-request-predicates-factories
          predicates:
            - Path=/api/account/**,/api/notify/** # 符合该路由条件的就代理到user-service
            - After=2013-01-20T17:42:47.789-07:00[Asia/Shanghai] # 只有访问时间在配置时间之后才能访问
          filters: # 过滤器
            - AddRequestHeader=X-key, hello
        - id: linklyze-link
          uri: lb://linklyze-link
          predicates:
            - Path=/link/**
