server:
  port: 8081
#  servlet:
#    context-path: /api

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    com.linklyze: debug
#  pattern:
#    # 要交双引号
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p ${PID:-} [%15.15t] %-40.40logger{39} %L : %m%n"

pay:
  alipay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq2HYHZUuU+vpjwnE5rj8ubexW1PiLQs0/TG+nkRAGjkCYFffa7aj/gCCBnXRmbVq0bHDUMfbUNcecdK/9qX1O7ohVzxVGAm1WEObsBbaTIn0FyjMNLyJip7drvPSaiohcMH9aM+Cq87e5+NhKr9PDCoJmqaWUDCIiXai5RL0mXggtVO+z99v0RuIIn1SIt22Gm78xhQ0IU3tGYTqgaCHoDdwgf6F5p3Gk3MtU307nCtno7anDlDv8Aj39oMmMnPRuxUqJ1PJWW/sImwDavF6GlYJqNE0wVeCanOYvyiKkQMU72l1P6W5yEBQc6kPgcHujVUjsA8VJPjgs9rrW0yzOQIDAQAB
    app-id: 9021000128698010
    charset: UTF8
    format: json
    notify-url: https://eb04-183-3-180-253.ngrok-free.app/api/pay/callback
    private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDQztJnZJ9NE07lD2VuTnfKTI5bgY2v0IapRNrOEd89NCU/p88Qhz9QOzhzBLAjZuXdVjpwZKenqgT1DW/QJBudqzJ8E7iMHIEVstEE7WAge03P+wJtiGaPRkmy/3nC3m6k0LKpihQwDBLcUX1bFGykWN5lLRzibb0Eyx7ATX2HN/Of2fHCo2WNb8ow+sZOxOlOtPnrxYHLlVTn4nkNIS7zwXLimbsbJVF5Acrur0X3saKwNImeHwXPYX493ZWK8gOJQ72bhtnNidcbTh1N8sJVc7NzIpqs0gPVKJYiQeKQfiAgdXTm/FZgl1kSjdtNbqNlHTNu/81yUioZURE6Ob2RAgMBAAECggEAfe/v2OpIZi06DU9e5suu1jWcOraFpT+IqHjd2yHOWdSkjqMAcUCRQCunnT97mK6L/xXtwzICKE6UFNSY1pmgilTh6xHd4aujc1nZVTZyHsUfpkwHJ9b3vHwxISOS5aRQaVlyGG0uRdhSW81OZOuJpwnugGlYHX0AXu6/Sk6yYiWV81kt+U9oTLAlXQBCiVNgdlc5LekC/yZYpKrQlDRAPyyxKtbzgj8NCWCLk7USpXzkWqQbgpT8fQWCES+FllvyheML/Ao9S+5sev4hN/dBm6j4ZN6R3ZRG9gB99iB76EBR3Tu3M3+rL8YOJIPf+KeVuT7bX38lZZbo55WQ7zyDEQKBgQD8btXIODs6ZKndIHMuCnRJfhyph6xqwZNKN3qeA/Ay30T35dQxIQztUlL572yfBTJ+S9PaNkb/jQtzr9FaYuLIa5CnIVdcQPKLWWuNJz53qblk3uznjKCp20n9h2TBMSGCYkxRJlufsZ7FNSMDZeIIFcivAGOx+HNH/8XpWCTpRQKBgQDTwizVSJiJy2W3TS3JdzcJYo9QjvwWpJoTEC9Yhq7KGPLyqi5zb+g/uVkNwkDRJSIynHmRNrwzWVxCF/TVKFJSmD7uWrHk8LbfgvEMwpRkCkaTlN7gVnwtrk3j1uRy3NTJ2ewMuGdDCOJF1ND7gmNKQ1NFEcBqbw8ptvQ1iXw53QKBgQCu2crk8+Y6rU1nqLl/c6hW267Y0uxfyhPO/ZzGZS303ugz2hNfsGf23uYwz2HqyDvQdY+Z/6ywCK+dA3S86e/yKWe6DIMpmKcoVNkFneBMHNkZAL0SKjuDTCz1Gtp0Yya13IbGUw52EB9MtGC7Us/9D7HBXkCwHssjXQxmdDKlDQKBgQCqgA3ZLTqkuECN9naHYJXP2KvMEVSoZqAn+UAl50uVLcFv4dbE27YEmRg7G81UmLGQTq0TXx7puWmvTdq0RmMCXdNN13ik/axBCw1LWOBiLGPnMFbECt6xaUcNzFjkoyox3GVTWKbMMrr9vv0FhVas1MiXNFPZXtK2o7i94pVDgQKBgQDG7Coc887N8EatePzOzQgrGe05AZcI4ObWJ25bg1n0LjprUTlFP2FxVAn6X5MEHHNhGEZ6u3O0EBLc+2gsBD22UjZmDL2Gpjzu8e7Il1GQY/mhEFwijDXDO80LUCB96yZbTe6Itt/np8VAmdLlhkGWXv3+9dCAsqsYQylgqqNneQ==
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    sign-type: RSA2
